To set mtu on private network
ocp-power-automation/ocp4-upi-powervm pull request #229
Opened 2021-12-14 06:55 UTC by aishwaryabk

Signed-off-by: Aishwarya Kamat <aishwarya.kamat@ibm.com>

2021-12-24 02:19 UTC, yussufsh requested changes
Could you also add it in var.tfvars?

2021-12-24 02:19 UTC, yussufsh commented on modules/5_install/install.tf
> +  triggers = {
Is this trigger needed? Why?

2021-12-24 07:50 UTC, aishwaryabk commented on modules/5_install/install.tf
> +  triggers = {
Yes, it could be done without triggers.

2021-12-24 07:51 UTC, aishwaryabk commented
> Could you also add it in var.tfvars?

@yussufsh I have added "private_network_mtu" to the var.tfvars file.

2021-12-28 03:04 UTC, yussufsh commented
@aishwaryabk Please help with the conflicts.

2021-12-29 05:42 UTC, aishwaryabk commented
> @aishwaryabk Please help with the conflicts.

@yussufsh The conflicts are resolved.

2021-12-29 06:03 UTC, yussufsh approved these changes
/lgtm

2022-01-05 15:11 UTC, cs-zhang approved these changes
/lgtm

2022-02-09 20:48 UTC, merged