-s
ocp-power-automation/ocp4-upi-powervm pull request #276
Opened 2023-10-17 14:21 UTC by gauravpbankar

Draft for fips for bastion change

2023-10-17 15:40 UTC, prb112 commented on modules/1_bastion/bastion.tf
> +
```suggestion
```

Duplicate line

2023-10-17 15:40 UTC, prb112 commented on modules/1_bastion/bastion.tf
> +resource "null_resource" "bastion_nop" {
```suggestion
resource "null_resource" "fips_enablement" {
```

2023-10-17 15:42 UTC, prb112 requested changes
needs changes

2023-10-18 17:25 UTC, prb112 commented on modules/1_bastion/bastion.tf
> +
```suggestion

```

2023-10-18 17:25 UTC, prb112 commented on modules/1_bastion/bastion.tf
> +sudo shutdown -r +1
```suggestion
  count = var.fips_compliant ? local.bastion_count : 0
  depends_on =  [ null_resource.fips_enablement ]
  connection {
    type        = "ssh"
    user        = var.rhel_username
    host        = openstack_compute_instance_v2.bastion[count.index].access_ip_v4
    private_key = var.private_key
    agent       = var.ssh_agent
    timeout     = "${var.connection_timeout}m"
  }
  provisioner "remote-exec" {
    inline = [
      <<EOF
whoami
```

2023-10-18 17:26 UTC, prb112 commented on modules/1_bastion/bastion.tf
> +
```suggestion
  count = var.fips_compliant ? local.bastion_count : 0
  depends_on =  [ openstack_compute_keypair_v2.key-pair ,random_id.label ,openstack_compute_flavor_v2.bastion_scg, openstack_compute_instance_v2.bastion, null_resource.bastion_init, null_resource.setup_proxy_info, null_resource.bastion_register, null_resource.enable_repos, openstack_blockstorage_volume_v3.storage_volume, openstack_compute_volume_attach_v2.storage_v_attach, null_resource.bastion_init , null_resource.setup_nfs_disk]
  connection {
    type        = "ssh"
    user        = var.rhel_username
    host        = openstack_compute_instance_v2.bastion[count.index].access_ip_v4
    private_key = var.private_key
    agent       = var.ssh_agent
    timeout     = "${var.connection_timeout}m"
  }
  provisioner "remote-exec" {
    inline = [
      <<EOF
# enable FIPS as required
sudo fips-mode-setup --enable
# rebooting bastion node
sudo shutdown -r +1
EOF
    ]
  }
}

```

2023-10-25 09:30 UTC, gauravpbankar commented on modules/1_bastion/bastion.tf
> +
Added changes.

2023-10-25 09:44 UTC, prb112 commented on modules/1_bastion/bastion.tf
> +
```suggestion
```

2023-10-25 09:44 UTC, prb112 commented on modules/1_bastion/bastion.tf
> +
target terraform style does not add a return

2023-10-25 09:44 UTC, prb112 commented on modules/1_bastion/bastion.tf
> +
please also run a terraform fmt on the code

2023-10-25 09:45 UTC, prb112 commented on modules/1_bastion/bastion.tf
> +
target style does not have a return
```suggestion
```

2023-10-25 09:45 UTC, prb112 commented on modules/1_bastion/bastion.tf
> +
```suggestion

# This step waits for the bastion to come back up and runs a simple command
```

2023-10-25 09:45 UTC, prb112 commented on modules/1_bastion/bastion.tf
> +
Add comment

2023-10-25 09:46 UTC, prb112 commented on modules/1_bastion/versions.tf
> +      version = "0.9.1"
This is a new dependency to facilitate synchronization between null_resource providers

2023-10-25 09:48 UTC, prb112 commented on ocp.tf
> +  depends_on = [module.bastion]
Added due to module level synchronization problems when FIPS is enabled.

There is an option to use a small dummy step that uses fips_compliant as the synchronization point only when fips is enabled. We opted for this cleaner approach.

2023-10-25 09:48 UTC, prb112 requested changes
Please make the few style changes, and change from work in progress to ready for review.

2023-10-25 12:15 UTC, prb112 requested changes
comments are inline

2023-10-25 12:41 UTC, gauravpbankar commented
@yussufsh : 
Please review the PR.

2023-10-25 12:56 UTC, yussufsh commented
/ok-to-test

2023-10-25 13:07 UTC, yussufsh commented
> @yussufsh : Can you please review the PR.

@gauravpbankar  There are syntax errors in the code. When you are making any further changes I want to see a full run log with the required variables.
Please assign PRs only when you have a working code otherwise it is a waste of time for reviewers.
@prb112

2023-10-25 13:46 UTC, prb112 commented
Hey @Gaurav / @yussufsh yes - I totally agree. please ping the log to Yussuf and I

2024-07-12 15:16 UTC, yussufsh commented
I am going to close this PR, if needed please raise a new one.

2024-07-12 15:16 UTC, closed without merging

2024-07-12 15:21 UTC, prb112 commented
still needed, new PR will come with new dev