Provision to use alternate repos for helpernode and playbooks
ocp-power-automation/ocp4-upi-powervm pull request #94
Opened 2020-08-13 11:05 UTC by Prajyot-Parab

Signed-off-by: Prajyot Parab <prajyot.parab@ibm.com>

2020-08-13 11:51 UTC, yussufsh requested changes

2020-08-13 11:51 UTC, yussufsh commented on variables.tf
> +    # Repo for running ocp4 installations steps.
Update the comment please

2020-08-13 11:55 UTC, bpradipt commented
@Prajyot-Parab can you please tag this to an issue/feature request

2020-08-13 12:09 UTC, Prajyot-Parab commented
> @Prajyot-Parab can you please tag this to an issue/feature request

@bpradipt Done

2020-08-13 12:20 UTC, yussufsh approved these changes

2020-08-13 16:54 UTC, bpradipt commented
@Prajyot-Parab since we are adding support for alternate repos, I would like to see an option to use zip or tar.gz of the helpernode and playbook. Would this make sense to incorporate into this patch  - Support for alternate repos and format ?

2020-08-13 16:58 UTC, Prajyot-Parab commented
> @Prajyot-Parab since we are adding support for alternate repos, I would like to see an option to use zip or tar.gz of the helpernode and playbook. Would this make sense to incorporate into this patch - Support for alternate repos and format ?

@bpradipt I can explore on that and push it as a separate patch.

2020-08-13 19:07 UTC, bpradipt commented
ok @Prajyot-Parab please explore that as it will be critical for completely disconnected install.

2020-08-13 19:07 UTC, bpradipt approved these changes
/lgtm
Thanks @Prajyot-Parab

2020-08-13 19:07 UTC, merged

2020-08-14 06:54 UTC, yussufsh commented
> 
> 
> @Prajyot-Parab since we are adding support for alternate repos, I would like to see an option to use zip or tar.gz of the helpernode and playbook. Would this make sense to incorporate into this patch - Support for alternate repos and format ?

With tar/gz/zip there are various validations for type of archive and directory structure. It is complex and need to create an issue for this.

2020-08-14 06:56 UTC, yussufsh commented
We can work with this one https://github.com/ocp-power-automation/ocp4-upi-powervm/issues/30